### ISSUE TITLE
Добавить авторизацию

### ISSUE THREAD

**Issue by ramazanmamedov** [glokzs/HSCFiscal#10]
**Необходимо добавить авторизацию ККМ в нашей API**
На данный момент мы не можем двигаться дальше, так как не можем авторизоваться в системе, без авторизации невозможно отправить запрос в тестовый ОФД.

**Что требуется**
- Сбор информации по авторизации в Web API приложениях.
- Добавить регистрацию и авторизацию ККМ в системе.
- Каждый раз при отправке логина и пароля должен выдаваться новый уникальный токен.
- Ограничить жизненный цикл токена.

**Ожидаемое поведение**
При отправке запроса на авторизацию в запросе содержится логин и пароль, при успешной авторизации в ответе должен содержаться уникальный токен. Ошибки пока не учитываем.

_Документация с примером авторизации_
https://github.com/YunussovIvraimjan/HSCFiscal/wiki/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F

_Статья на тему Аутентификация и авторизация на основе токенов (metanit.com)_
https://metanit.com/sharp/aspnet_webapi/5.1.php

_Статья на тему Регистрация, авторизация, получение и использование токена (metanit.com)_
https://metanit.com/sharp/aspnet_webapi/5.2.php 

_Статья на MSDN на тему аутентификации с использованием JWT_
https://msdn.microsoft.com/ru-ru/mt790175.aspx

**_Оценка времени : ~12 часов_**

**Comment by YunussovIvraimjan** [comment]
Регистрация и смена пароля добавлена

**Comment by YunussovIvraimjan** [comment]
регистрацию и смену пароля перекинул в ветку feature10.1 из девелоп, сам девелоп откатил до предыдущего коммита

**Comment by YunussovIvraimjan** [comment]
исправил ошибку, когда возвращались три неизвестных поля
