### ISSUE TITLE
Запись ответов с API ОФД в Log файл

### ISSUE THREAD

**Issue by ramazanmamedov** [glokzs/HSCFiscal#11]
**Что необходимо**
Записать ответы, которые приходят с ОФД в Log файл.

**Что требуется**
На данный момент в API реализована отправка запросов и получение ответов от API ОФД. Нужно добавить реализацию записи ответов в Log файл, т.к на данный момент мы не имеем БД, а хранить ответы где то нужно. Также логи позволяют 

- Реализовать метод записи в Log файл в отдельном статическом классе и определить как сервис (папка 
- Реализовать возможность считать данные с Log файла

**Что ожидается**
- Мы отправляем запрос в ОФД
- Мы принимаем ответ с ОФД и записываем его в Log файл 

_Документация по библиотеке NLog для логирования проекта_ https://itvdn.com/ru/blog/article/logging-project-with-nlog-framework

_Установка и настройка NLog_
https://subreal-team.com/c-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-nlog/

_NLog официальная документация_
https://nlog-project.org/

**_Оценка времени : ~5 часов_**

**Comment by YunussovIvraimjan** [comment]
Добавил сущности для ответа от апк сервера к ккм

**Comment by Zhassulan7** [comment]
Добавил библиотеку NLog, NLog.Config, реализовал сервис LogWriteService, со статичным методом для записывания в лог данных LogWrite(), добавил в MoneyPlacementController LogWriteService, ответ от апи записывается в лог, который находится в директории bin.
