### ISSUE TITLE
Написать тикеты разработчикам

### ISSUE THREAD

**Issue by ramazanmamedov** [glokzs/HSCFiscal#15]
**Что нужно сделать**
Аналитику и капитану нужно определить дальнейшие действия команды. Написать тикеты и  вместе с командой определить время и силы, необходимые для реализации задач.

Аналитику необходимо проанализировать текущие тикеты и определить в них места, которые нужно исправить либо дополнить.

_Время на реализацию : 2 часа_

**Comment by NurOrNuLL** [comment]
_Аналитику и капитану нужно определить дальнейшие действия команды._

Было решено взять в приоритет авторизацию ККМ на сервере.

_Написать тикеты и вместе с командой определить время и силы, необходимые для реализации задач._

Задача была разделена на три части 

1. Авторизация на сервере
2. Проверка токена при запросе со сторы ККМ
3. DataSeed - тестовые данные для заполнения данными пользователя в БД

Время выполнения задачи на команду 10 часов, крайний срок выполнения до 22/08.

_Аналитику необходимо проанализировать текущие тикеты и определить в них места, которые нужно исправить либо дополнить._

1. необходимо переписать тикет номер 10 и дополнить недостающей информации, выполнять тикет будет @YunussovIvraimjan 
2. Создать два тикета для @VitaliyPasko "создание seed информации" и @Zhassulan7  "проверка токена"
