### ISSUE TITLE
Проверка токена

### ISSUE THREAD

**Issue by NurOrNuLL** [glokzs/HSCFiscal#16]
Задача: проверка токена на валидность

Необходимо реализовать проверку токена при отправке запроса со строны клиента, т.е при получении запроса в теле запроса имеется поле "токен", необходимо проверить совпадают ли токен клиента с токеном выданным при авторизации. в случае не соответствия токена выдать ошибку 1 [смотреть на документацию](https://docs.google.com/document/d/1K7wTl6PehEwQCPx-0HLdRn9FimOO6gNt76wsl0RhVvE/edit)

**Comment by YunussovIvraimjan** [comment]
Валидность токена работает некорректно, тикет открыт для доработки
