### ISSUE TITLE
Переход на тестовый сервер

### ISSUE THREAD

**Issue by VitaliyPasko** [glokzs/HSCFiscal#23]
Необходимо развернуть HSCFiscal на тестовом сервере.
Операционной системой для тестового сервера должна быть Linux.

**Comment by ramazanmamedov** [comment]
Приступил 27.08.19 в 12.52

**Comment by ramazanmamedov** [comment]
Изучил особенности Docker. Собрал образ под Linux из под Windows. Отправил Docker образ на тестовый сервер, развернул Docker контейнер на сервере. На данный момент приложение крутится на сервере внутри Docker контейнера. Осталась проблема доступа к приложению и проброс реальных портов на виртуальныt. Сервер не пингуется извне.

Закончил 30.08.19 в 18:30
