### ISSUE TITLE
Анализ аппаратно-програмного комплекса MultiBank

### ISSUE THREAD

**Issue by VitaliyPasko** [glokzs/HSCFiscal#24]
Задача.
1. Изучить документацию программного комплекса MultiBank.
2. Описать структуру моделей и объектов.
3. Изучить коды ошибок.
4. Оценить объем работы и написать план по реализации программного комплекса.

**Comment by YunussovIvraimjan** [comment]
Задачи тикета были переопределены. Данный тикет ушёл на переработку и будет описан позже уже в другом тикете.
Данный тикет закрыт.
