### ISSUE TITLE
Получения списка касс пользователя

### ISSUE THREAD

**Issue by VitaliyPasko** [glokzs/HSCFiscal#25]
У каждого пользователя есть кассовый аппарат. Нужно осуществить возможность отправки запроса списка данных по каждому кассовому аппарату какого-либо пользователя.

1. Создать сущность кассового аппарата.
2. Описать ее поля.
3. Создать контроллер, который будет отправлять токен пользователя, а ответ получать данные по каждому из всех кассовых аппаратов нужного нам пользователя.

Необходимые классы и поля для реализации данного контроллера можно найти здесь: https://docs.google.com/spreadsheets/d/1-8SEOw2Gv0mn3gNOrRsFwVdehkgGdNHbFUZCw91hpD8/edit?usp=sharing

**Comment by YunussovIvraimjan** [comment]
Тикет был ассимилирован с #30 и отдан на работу другому разработчику
