### ISSUE TITLE
Реализовать отправку запроса на получение информации о кассе

### ISSUE THREAD

**Issue by Zhassulan7** [glokzs/HSCFiscal#3]
Нужно реализовать запрос "на получение информации о кассе" через API в ОФД и получить ответ от ОФД. Тестовый сценарий прилагается в документации
Документация прилагается:
1)https://drive.google.com/file/d/1uE1QwVezPCeiMQfK1fFBKKEopzIS7BT9/view
2)https://docs.google.com/document/d/1E9INbxMNUgTsjR1RMxu5cM3Tm2ExQ2YjE-L2_uKP7V8/edit?usp=sharing
Ссылка на вики с примерами и таблицами
https://github.com/YunussovIvraimjan/HSCFiscal/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-%D0%BA%D0%B0%D1%81%D1%81%D0%B5

**Comment by NurOrNuLL** [comment]
Задача выполнена. Ответ от ОФД получен! 

скрин:

[https://prnt.sc/oquqdv](url)
