### ISSUE TITLE
Запрос на получение информации о кассе

### ISSUE THREAD

**Issue by YunussovIvraimjan** [glokzs/HSCFiscal#30]
Задачи: 
1)Создать модель для отправки запросов в ОФД и сохранить данные в БД
2)Получить ответ от ОФД, обработать его и сохранить отдельные поля в БД(либо обновить)
Что нужно:
Для того чтобы получить данные о кассе нам нужно отправить запрос с определенными полями, которые будут храниться в БД, также эти поля нам понадобятся в будущем для других запросов.
Запрос на получение информации о кассе можно отправлять через postman
Первый токен нужно взять из test-ofd, в последующем уже работать с тем токеном, что мы получаем от ОФД
Из ответа от ОФД нужно сохранить объект reg_info с его вложенностями.
Также токен юзера и токен ОФД должны быть привязаны к определенную пользователю
Информацию по получению информации о кассе можно взять здесь:
https://github.com/glokzs/HSCFiscal/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE-%D0%BA%D0%B0%D1%81%D1%81%D0%B5
Также дополнительная информация по другим запросам:
https://docs.google.com/document/d/1_bvbFphZm4rQRx5iNChKhBk3YbyivPJ-n3eTp6cC7W0/edit
P.S. иногда приходит отрицательный токен от ОФД, желательно проверить работает ли он корректно, то есть отправить его обратно в ОФД и получить по нему данные

**Comment by ramazanmamedov** [comment]
Тикет приостановлен. Нет доступа к ОФД, невозможно получить данные для отправки запроса.
