### ISSUE TITLE
Дорожная карта ОФД

### ISSUE THREAD

**Issue by YunussovIvraimjan** [glokzs/HSCFiscal#35]
Необходимо создать "дорожную карту" ОФД. То есть описать все сущности, которые мы передаём и получаем от ОФД, найти закономерности и описать повторяющиеся поля.

**Comment by VitaliyPasko** [comment]
https://docs.google.com/spreadsheets/d/1-8SEOw2Gv0mn3gNOrRsFwVdehkgGdNHbFUZCw91hpD8/edit#gid=0 - ссылка на карту.
