### ISSUE TITLE
Реализовать отправку запроса на внесение и снятие наличных денежных средств

### ISSUE THREAD

**Issue by Zhassulan7** [glokzs/HSCFiscal#4]
Нужно реализовать запрос "Внесение и снятие наличных денежных средств" через API в ОФД
Получить данные от ОФД
Документация прилагается:
1)https://drive.google.com/file/d/1uE1QwVezPCeiMQfK1fFBKKEopzIS7BT9/view
2)https://docs.google.com/document/d/1E9INbxMNUgTsjR1RMxu5cM3Tm2ExQ2YjE-L2_uKP7V8/edit?usp=sharing

**Comment by ramazanmamedov** [comment]
Тикет #4 выполнен, получение данных, отправка и получение запроса по команде #6(Внесение/снятие наличных) реализованы. 
http://prntscr.com/oqvy9q
