### ISSUE TITLE
Создание архитектуры приложения

### ISSUE THREAD

**Issue by ramazanmamedov** [glokzs/HSCFiscal#9]
**Необходимо создать архитектуру приложения**
На данный момент мы не имеем общей архитектуры приложения, разработчики дублируют код, во время выполнения своих задач. 

**Что требуется**
- Продумать концепцию, по которой будут определяться модели ответов и запросов
- Определить архитектуру для дальнейшей работы
- Определить связи для моделей(классов) API.
- Определить структуру папок
- Соблюдать структуру запросов и ответов.

**Что нам это даст**
Мы будем работать в структурированном и хорошо продуманном приложении. Не будет проблем с дублированием кода и выполнением одних и тех же задач.

_Примеры запросов в ОФД_
https://docs.google.com/document/d/1_bvbFphZm4rQRx5iNChKhBk3YbyivPJ-n3eTp6cC7W0/edit

_Документация по API АПК_
https://docs.google.com/document/d/1K7wTl6PehEwQCPx-0HLdRn9FimOO6gNt76wsl0RhVvE/edit

_Протокол Обмена ККТ_
https://drive.google.com/file/d/1uE1QwVezPCeiMQfK1fFBKKEopzIS7BT9/view

**_Оценка времени: ~8 часов._**

**Comment by YunussovIvraimjan** [comment]
Добавил сущности для отправки ответа от апк сервера к ккм

**Comment by YunussovIvraimjan** [comment]
Добавил классы для отправки ответа от апк сервера к ОФД, залил ветку в develop

**Comment by YunussovIvraimjan** [comment]
Работа над архитектурой завершена и запулена в ветку develop
